export const OTHERS_DETAILS_REQUEST = 'OTHERS_DETAILS_REQUEST';
export const OTHERS_DETAILS_SUCCESS = 'OTHERS_DETAILS_SUCCESS';
export const OTHERS_DETAILS_RESET = 'OTHERS_DETAILS_RESET';
export const OTHERS_DETAILS_FAIL = 'OTHERS_DETAILS_FAIL';

export const OTHERS_DETAILS_DELETE = 'OTHERS_DETAILS_DELETE';



export const ALL_OTHERS_DETAILS_REQUEST = 'ALL_OTHERS_DETAILS_REQUEST';
export const ALL_OTHERS_DETAILS_SUCCESS = 'ALL_OTHERS_DETAILS_SUCCESS';
export const ALL_OTHERS_DETAILS_RESET = 'ALL_OTHERS_DETAILS_RESET';
export const ALL_OTHERS_DETAILS_FAIL = 'ALL_OTHERS_DETAILS_FAIL';


export const DELETE_OTHERS_DETAILS_REQUEST = 'DELETE_OTHERS_DETAILS_REQUEST';
export const DELETE_OTHERS_DETAILS_SUCCESS = 'DELETE_OTHERS_DETAILS_SUCCESS';
export const DELETE_OTHERS_DETAILS_RESET = 'DELETE_OTHERS_DETAILS_RESET';
export const DELETE_OTHERS_DETAILS_FAIL = 'DELETE_OTHERS_DETAILS_FAIL';


export const SLIDER_DETAILS_REQUEST = 'SLIDER_DETAILS_REQUEST';
export const SLIDER_DETAILS_SUCCESS = 'SLIDER_DETAILS_SUCCESS';
export const SLIDER_DETAILS_RESET = 'SLIDER_DETAILS_RESET';
export const SLIDER_DETAILS_FAIL = 'SLIDER_DETAILS_FAIL';


export const SLIDER_UPDATE_REQUEST = 'SLIDER_UPDATE_REQUEST';
export const SLIDER_UPDATE_SUCCESS = 'SLIDER_UPDATE_SUCCESS';
export const SLIDER_UPDATE_RESET = 'SLIDER_UPDATE_RESET';
export const SLIDER_UPDATE_FAIL = 'SLIDER_UPDATE_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
